import 'package:hive/hive.dart';
import 'package:user_repository/src/models/user.dart';

part 'user_entity.g.dart'; // This file will be generated by running the build runner

@HiveType(typeId: 0) // Unique typeId to register UserEntity class with Hive
class UserEntity extends HiveObject {
  @HiveField(0)
  final String firstName;

  @HiveField(1)
  final String lastName;

  @HiveField(2)
  final String email;

  // @HiveField(3)
  // final String password;

  @HiveField(4)
  final String phoneNumber;

  @HiveField(5)
  final String gender;

  UserEntity({
    required this.firstName,
    required this.lastName,
    required this.email,
    // required this.password,
    required this.phoneNumber,
    required this.gender,
  });

  factory UserEntity.fromJson(Map<String, dynamic> json) {
    return UserEntity(
      firstName: json['first_name'],
      lastName: json['last_name'],
      email: json['email'],
      // password: json['password'],
      phoneNumber: json['phone_number'],
      gender: json['gender'],
    );
  }
  factory UserEntity.fromUser(User user) {
    return UserEntity(
      firstName: user.firstName,
      lastName: user.lastName,
      email: user.email,
      phoneNumber: user.phoneNumber,
      gender: user.gender,
    );
  }

  factory UserEntity.fill() {
    return UserEntity(
      firstName: '',
      lastName: '',
      email: '',
      // password: '',
      phoneNumber: '',
      gender: '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'first_name': firstName,
      'last_name': lastName,
      'email': email,
      // 'password': password,
      'phone_number': phoneNumber,
      'gender': gender,
    };
  }
}
